
###########################################################
# GCC template makefile
###########################################################

ESP_SOURCES =
ESP_SOURCES += ESP8266.c

C_SOURCES += $(ESP_SOURCES)