
###########################################################
# GCC template makefile
###########################################################


MENU_SOURCES = menu.c
MENU_SOURCES += at_menu.c


C_SOURCES += $(MENU_SOURCES)