
###########################################################
# GCC template makefile
###########################################################

MENU_SOURCES = \
MENU_SOURCES += menu.c


C_SOURCES += $(MENU_SOURCES)